# Site settings
title: "cub|e|vo blog"
description: "About optimizing work using technology."
url: "https://blog.cubevodata.com"
author:
  name: "Cubevo Data Concept"
  email: "contact@cubevodata.com"
  url: "https://blog.cubevodata.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-shift-return-github-io-blog
    
